/**
 * Credits Scene - End credits with historical context
 */

const CreditsScene = {
    id: 'credits',
    name: 'Credits',
    
    background: 'assets/images/scenes/credits.svg',
    
    description: 'Thank you for playing CyberQuest: Operation ZERFALL',
    
    playerStart: { x: 50, y: 50 },
    
    hotspots: [],
    
    onEnter: (game) => {
        // Show full credits
        setTimeout(() => {
            game.startDialogue([
                { speaker: '', text: '═══════════════════════════════════════' },
                { speaker: '', text: 'CYBERQUEST: OPERATION ZERFALL' },
                { speaker: '', text: '═══════════════════════════════════════' },
                { speaker: '', text: '' },
                { speaker: '', text: 'GAME DESIGN & DEVELOPMENT' },
                { speaker: '', text: 'Rein Velt' },
                { speaker: '', text: '' },
                { speaker: '', text: 'CHARACTERS' },
                { speaker: '', text: 'Ryan Weylant - Dutch Hacker' },
                { speaker: '', text: 'Eva Weber - IT Security Analyst (Whistleblower)' },
                { speaker: '', text: 'Dr. Henk Visser - ASTRON Radio Astronomer' },
                { speaker: '', text: 'Chris Kubecka - Cybersecurity Expert' },
                { speaker: '', text: 'Dr. Dmitri Volkov - Russian Scientist' },
                { speaker: '', text: 'Marieke - LOFAR Technician (Retired)' },
                { speaker: '', text: 'Pieter - Ericsson Bluetooth Engineer' },
                { speaker: '', text: '' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: 'BASED ON REAL TECHNOLOGY & EVENTS' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: '' },
                { speaker: '', text: 'MESHTASTIC NETWORKS' },
                { speaker: '', text: 'Real off-grid communication technology using LoRa radio.' },
                { speaker: '', text: 'Used worldwide by privacy advocates, hikers, and emergency responders.' },
                { speaker: '', text: 'Truly decentralized - no internet, no cell towers required.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'FLIPPER ZERO' },
                { speaker: '', text: 'Actual multi-tool device for hardware hacking and RF analysis.' },
                { speaker: '', text: 'Used by security researchers to test wireless systems.' },
                { speaker: '', text: 'Released in 2022, became popular in hacker communities.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'CHRIS KUBECKA' },
                { speaker: '', text: 'Real cybersecurity expert who worked on major incidents.' },
                { speaker: '', text: 'Helped Saudi Aramco recover from devastating cyberattack.' },
                { speaker: '', text: 'Now works with international organizations on cyber defense.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'TER APEL MONASTERY' },
                { speaker: '', text: 'Real 15th-century monastery in Groningen, Netherlands.' },
                { speaker: '', text: 'Now a museum, historically a meeting place for secretive groups.' },
                { speaker: '', text: 'Located near the German border in quiet countryside.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'STECKERDOSER HEIDE' },
                { speaker: '', text: 'Fictional location inspired by real military testing areas.' },
                { speaker: '', text: 'Similar restricted zones exist throughout Germany.' },
                { speaker: '', text: 'Used for defense research and weapons development.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'RADIO FREQUENCY WEAPONS' },
                { speaker: '', text: 'Actual area of military research since the 1950s.' },
                { speaker: '', text: 'High-power microwave weapons can disable electronics.' },
                { speaker: '', text: 'Concerns about health effects remain debated.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'CHAOS COMPUTER CLUB (CCC)' },
                { speaker: '', text: 'Europe\'s largest hacker association, founded 1981 in Germany.' },
                { speaker: '', text: 'Annual Congress in Hamburg brings together security researchers.' },
                { speaker: '', text: 'Advocates for transparency, privacy, and digital rights.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'GERMAN INTELLIGENCE (BND)' },
                { speaker: '', text: 'Real German foreign intelligence agency.' },
                { speaker: '', text: 'Works closely with NATO allies on cyber threats.' },
                { speaker: '', text: 'Located in Berlin with operations across Europe.' },
                { speaker: '', text: '' },
                { speaker: '', text: 'DUTCH INTELLIGENCE (AIVD)' },
                { speaker: '', text: 'Netherlands\' General Intelligence and Security Service.' },
                { speaker: '', text: 'Known for sophisticated cyber operations.' },
                { speaker: '', text: 'Headquarters in The Hague.' },
                { speaker: '', text: '' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: 'FICTIONAL ELEMENTS' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: '' },
                { speaker: '', text: 'Operation ZERFALL is fictional.' },
                { speaker: '', text: 'Dr. Dmitri Volkov is a fictional character.' },
                { speaker: '', text: 'Ryan Weylant is fictional.' },
                { speaker: '', text: 'Eva Weber is fictional.' },
                { speaker: '', text: 'Specific plot events are dramatized for storytelling.' },
                { speaker: '', text: '' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: 'INSPIRATION' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: '' },
                { speaker: '', text: 'This game was inspired by:' },
                { speaker: '', text: '• Real events in cybersecurity and intelligence' },
                { speaker: '', text: '• The hacker ethic of transparency and accountability' },
                { speaker: '', text: '• Classic point-and-click adventure games' },
                { speaker: '', text: '• The Dutch countryside and its hidden history' },
                { speaker: '', text: '• Concerns about weaponized technology' },
                { speaker: '', text: '' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: 'SPECIAL THANKS' },
                { speaker: '', text: '─────────────────────────────────────' },
                { speaker: '', text: '' },
                { speaker: '', text: 'To the Chaos Computer Club community' },
                { speaker: '', text: 'To Meshtastic developers and users' },
                { speaker: '', text: 'To security researchers who keep us safe' },
                { speaker: '', text: 'To everyone fighting for digital rights' },
                { speaker: '', text: '' },
                { speaker: '', text: '═══════════════════════════════════════' },
                { speaker: '', text: 'THANK YOU FOR PLAYING' },
                { speaker: '', text: '═══════════════════════════════════════' },
                { speaker: '', text: '' },
                { speaker: '', text: '© 2026 Rein Velt' },
                { speaker: '', text: 'A CCC-inspired cybersecurity adventure' },
                { speaker: '', text: '' },
                { speaker: '', text: '[Click to return to title screen]' }
            ]);
        }, 500);
    },
    
    onExit: () => {
        // Could add return to title screen functionality
    }
};
